# Generated by Django 5.0.3 on 2024-03-19 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250, verbose_name='Título')),
                ('fecha_alta', models.DateField(auto_now_add=True, verbose_name='Fecha de alta')),
                ('estado', models.CharField(choices=[('ABIERTO', 'ABIERTO'), ('CERRADO', 'CERRADO')], max_length=50, verbose_name='Estado')),
                ('fecha_estado', models.DateField(verbose_name='Fecha del estado')),
                ('fecha_limite', models.DateField(verbose_name='Fecha de cierre')),
                ('fecha_cierre', models.DateField(verbose_name='Fecha de cierre')),
                ('descripción', models.TextField(verbose_name='Descripción')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Accion',
                'verbose_name_plural': 'Acciones',
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_evaluacion', models.TextField(verbose_name='Evaluación')),
                ('causas', models.CharField(choices=[('CAUSA-A', 'CAUSA-A'), ('CAUSA-B', 'CAUSA-B')], max_length=250, verbose_name='Causas')),
                ('acciones', models.ManyToManyField(to='gestion_eventos.accion', verbose_name='Acciones')),
                ('evaluador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Evaluador')),
            ],
            options={
                'verbose_name': 'evaluación',
                'verbose_name_plural': 'evaluaciones',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250, verbose_name='Título')),
                ('fecha_alta', models.DateField(auto_now_add=True, verbose_name='Fecha de alta')),
                ('fecha_evento', models.DateField(verbose_name='Fecha del evento')),
                ('estado', models.CharField(choices=[('ABIERTO', 'ABIERTO'), ('CERRADO', 'CERRADO')], max_length=50, verbose_name='Estado')),
                ('fecha_estado', models.DateField(verbose_name='Fecha del estado')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('clasificacion', models.CharField(choices=[('GRAVE', 'NIVEL 1'), ('LEVE', 'NIVEL 2')], max_length=50, verbose_name='Clasificación')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gestion_eventos.evaluacion', verbose_name='Evaluación')),
                ('responsable_cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de cierre')),
                ('usuario_alta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que da de alta')),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
            },
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='evento_asociado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gestion_eventos.evento', verbose_name='Evento'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='eventos_repetitivos',
            field=models.ManyToManyField(related_name='+', to='gestion_eventos.evento', verbose_name='Eventos repetitivos'),
        ),
        migrations.AddField(
            model_name='accion',
            name='evento_asociado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gestion_eventos.evento', verbose_name='Evento'),
        ),
    ]
