# Generated by Django 5.0.3 on 2024-03-19 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='evaluacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gestion_eventos.evaluacion', verbose_name='Evaluación'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_estado',
            field=models.DateField(blank=True, editable=False, verbose_name='Fecha del estado'),
        ),
    ]
